name: Main

on:
  pull_request:
    branches:
      - dev
      - production
  push:
    branches:
      - dev
      - production

jobs:
  build-and-lint:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Install packages
      run: npm install

    - name: Build
      run: npm run build

    - name: Run eslint
      run : npm run lint

    - name: Commit prettier changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "auto commit: apply eslint fixes"
  tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Install Dependencies
      run: npm install

    - name: Run tests
      run: docker compose run test

    - name: Stop containers
      if: always()
      run: docker compose down