name: e2e tests

on: [pull_request]

jobs:
  e2e:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Install Dependencies
      run: npm install

    - name: Run tests
      run: docker compose run test

    - name: Stop containers
      if: always()
      run: docker compose down